[Config]

### If your RaceMenu dll has a different name than "skee64.dll"/"skeevr.dll", you can define it here,
### and the address offsets for custom dlls (e.g. the UBE skee dll), can be set in skee_addresses.json

# skeeDllName="skee_custom.dll"


### Texture name used for clearing unused overlay slots: ###

# SlaveTats empty texture (is used per default)
# blankTextureName="Actors\Character\slavetats\blank.dds"

# Empty texture from RaceMenu
# blankTextureName="actors\character\overlays\default.dds"

# Same without path, probably also works
# blankTextureName="default.dds"


### Enable this, when you want to calculate the address offsets for a new skee dll,
### you probably also have to rename "SlaveTatsNG.dll" to "aaSlaveTatsNG.dll", or so
### (it must be loaded before the skee dll, otherwise the addresses are not dumped)
 
vmHook=false

### Middle, bottom and top slot ranges for the four areas body, face, hands and feet. ###

### Each range is specified by a minimum and maximum slot number. If the maximum slot number
### is negative, it is treated as relative to the total number of slots for this area. 
### And if the minimum slot number is greater than the maximum one, this defines an empty range
### with no slots.

### For example, if you have a total number of 30 slots for the body area, and define:

# SlotRange_Body_Middle_Min=3
# SlotRange_Body_Middle_Max=-3

### then this would tell SlaveTats to use only slots 3 - 27 for the middle layer of tattoos, 
### slots 0 - 2 and 28 - 29 would be left alone (for other mods (or slot ranges)). 

### Three slot ranges can be defined for each area: Middle, Bottom and Top

### The bottom layer can be used for tattoos which shall appear below everything else, e.g. veins, muscles, whip marks, spank tattoos.
### The middle layer can be used for normal tattoos, e.g. an anchor picture, or so.
### The top layer is for things which shall appear above everything else, e.g. dirt, blood, tears.

### If you want to specify that a tattoo shall use one of the three ranges, you can specify for your tattoo in the .json tattoos file for example :

#     area: "body"
#     slot_range: "bottom"      (or "top" or "middle" (middle is default, but can also be set explicitely))

### Per default, the middle slot range uses all available slots, and the top and bottom slot ranges are defined as empty
